#!/bin/bash
cd /workspaces/Perfect-Portable-Converter
git add -A
git commit -m "RELEASE: Apowersoft dark theme GUI ready - all features working"
git push origin main

echo ""
echo "✅ ✅ ✅ PUSHED TO GITHUB! ✅ ✅ ✅"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📦 DOWNLOAD LINKS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔗 Repository:"
echo "   https://github.com/Humming-SvKe/Perfect-Portable-Converter"
echo ""
echo "⬇️  Download ZIP:"
echo "   https://github.com/Humming-SvKe/Perfect-Portable-Converter/archive/refs/heads/main.zip"
echo ""
echo "📂 Clone via Git:"
echo "   git clone https://github.com/Humming-SvKe/Perfect-Portable-Converter.git"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✨ FEATURES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎨 Dark Theme (Apowersoft style)"
echo "   - Background: #2D2F38"
echo "   - Accent: #2FA9E0 (blue)"
echo "   - Modern flat design"
echo ""
echo "📋 Features:"
echo "   ✅ Add Files button (+ multi-select)"
echo "   ✅ Drag & Drop support"
echo "   ✅ Task list with 8 columns"
echo "   ✅ 5 tabs: Convert, Split Screen, Make MV, Download, Record"
echo "   ✅ Profile selector (5 presets)"
echo "   ✅ Output folder chooser"
echo "   ✅ Clear/Remove tasks"
echo "   ✅ Merge option"
echo "   ✅ Shutdown after conversion"
echo "   ✅ Big CONVERT button (420x130px, 22pt font)"
echo ""
echo "📏 Window Size: 1600x900"
echo "🔤 Font Size: 10pt base, 22pt CONVERT button"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🚀 HOW TO USE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Download ZIP from link above"
echo "2. Extract to folder (e.g. C:\\vcs\\Perfect-Portable-Converter)"
echo "3. Run START.bat"
echo "4. Click '+ Add Files' or drag & drop videos"
echo "5. Click CONVERT button"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
