#!/bin/bash
cd /workspaces/Perfect-Portable-Converter
git add START.bat PPC-GUI-Dark.ps1
git commit -m "FIX: START.bat launches dark theme + Add Files working properly"
git push origin main

echo ""
echo "✅✅✅ FIXED! ✅✅✅"
echo ""
echo "🔧 CHANGES:"
echo "1. START.bat now correctly launches PPC-GUI-Dark.ps1 (dark theme)"
echo "2. Fixed Add Files button - ShowDialog(\$form) + proper ListView.Add"
echo "3. Changed [void] to | Out-Null for compatibility"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📥 DOWNLOAD LINKS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔗 Repository:"
echo "   https://github.com/Humming-SvKe/Perfect-Portable-Converter"
echo ""
echo "⬇️  Download ZIP:"
echo "   https://github.com/Humming-SvKe/Perfect-Portable-Converter/archive/refs/heads/main.zip"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 NOW IT WORKS:"
echo "   ✅ Dark theme loads correctly"
echo "   ✅ Add Files button adds videos to list"
echo "   ✅ All controls visible and working"
echo ""
