name: Build Offline Release ZIP

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create folders
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path binaries,logs,temp,input,output,subtitles,overlays,thumbnails,licenses | Out-Null

      - name: Download FFmpeg (release essentials)
        shell: pwsh
        run: |
          $ErrorActionPreference='Stop'
          $url = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip"
          $zip = "temp\ffmpeg.zip"
          Invoke-WebRequest -Uri $url -OutFile $zip -UseBasicParsing
          Expand-Archive -Path $zip -DestinationPath "temp\ffmpeg" -Force
          $exe   = Get-ChildItem -Recurse -Filter ffmpeg.exe  -Path "temp\ffmpeg" | Select-Object -First 1
          $probe = Get-ChildItem -Recurse -Filter ffprobe.exe -Path "temp\ffmpeg" | Select-Object -First 1
          if (-not $exe -or -not $probe) { throw "Nenájdené ffmpeg/ffprobe v balíku." }
          Copy-Item $exe.FullName binaries\ffmpeg.exe    -Force
          Copy-Item $probe.FullName binaries\ffprobe.exe -Force
          New-Item -ItemType Directory -Force -Path licenses\ffmpeg | Out-Null
          Get-ChildItem -Recurse -Include LICENSE*,README* -Path "temp\ffmpeg" | ForEach-Object {
            Copy-Item $_.FullName licenses\ffmpeg\ -Force
          }

      - name: Compose ZIP
        shell: pwsh
        run: |
          $ErrorActionPreference='Stop'
          $ver = "${{ github.ref_name }}"
          $zip = "Perfect-Portable-Converter-$ver.zip"
          $items = @(
            "START.bat","PPC.ps1",".gitignore","LICENSE","README.md","config",
            "binaries","input","output","subtitles","overlays","thumbnails","logs","temp","licenses"
          )
          Compress-Archive -Path $items -DestinationPath $zip -Force

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: "Perfect-Portable-Converter-${{ github.ref_name }}.zip"
